apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipessoas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apipessoas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%      
  template:
    metadata:
      labels:
        app: apipessoas
    spec:
      containers:
      - name: apipessoas
        image: kuberneteshml.azurecr.io/apipessoas:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apipessoas-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: apipessoas